version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd client
      - npm ci
  build:
    commands:
      - mkdir -p reports/vitest
      - npx vitest run --reporter=junit --outputFile=./reports/vitest/junit.xml

reports:
  artofficial-vitest:
    files:
      - reports/vitest/junit.xml
    file-format: JUNITXML
