export const surpriseMePrompts = [
    'An armchair in the shape of an avocado',
    'A serene lake surrounded by mountains at sunrise',
    'Teddy bears shopping for groceries in Japan, ukiyo-e',
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'An astronaut lounging in a tropical resort in space, vaporwave',
    'An oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'A steaming cup of coffee on a wooden table with a croissant',
    'A garden maze viewed from above',
    'A cozy cabin in the woods surrounded by autumn leaves',
    'A tropical beach with crystal clear waters and palm trees',
    'A stack of pancakes with syrup and fresh berries',
    'A medieval castle atop a hill shrouded in mist',
    'A stained glass window depicting a hamburger and french fries',
    'A pencil and watercolor drawing of a bright city in the future with flying cars',
    'A train crossing a bridge over a river at dusk',
    'A futuristic train speeding through a tunnel',
    'A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'A painting of a fox in the style of Starry Night',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'A classic sailboat on calm waters during sunrise',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A modern living room with minimalist design elements',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A magical forest with glowing mushrooms and fairies',
    'An underwater scene with coral reefs and tropical fish',
    'A centered explosion of colorful powder on a black background',
    'A galaxy with swirling stars and colorful nebulae',
    'A photo of a white fur monster standing in a purple room',
    'A man standing in front of a stargate to another dimension',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A vibrant festival with lanterns and fireworks in the night sky',
    'A snowy mountain peak under a bright blue sky',
    'A modern skyscraper reflecting the sunset in a city skyline',
    'A field of glowing orbs in a dark forest',
    'A surreal landscape with floating islands and waterfalls',
    'A vibrant, side-scrolling landscape reminiscent of Super Mario, with whimsical mushroom-like structures and a colorful, obstacle-filled course',
    'A lighthouse on a cliff overlooking the sea during a storm',
    'A geometric pattern of triangles and circles in pastel shades',
    'A fractal pattern in vivid neon colors',
    'A giant pint glass full of golden beer',
    'A bouquet of roses in a vase on a wooden table',
    'A pizza fresh out of the oven with melted cheese and toppings',
    'A bustling city street at night with neon lights and people walking',
    'A cruise ship in a tropical harbor',
    'A dragon flying over a castle at dusk',
    'A quiet park in a city with benches and tall trees',
    'A bowl of ramen with chopsticks resting on the edge',
    'A wedding arch decorated with flowers on a beach',
    'A clock tower in a quiet town square at dusk'
  ];