import React, { useState, useEffect } from 'react';
import { Loader, Card, FormField, StatCard } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-[#10131f] text-xl uppercase">{title}</h2>
  );
};

const Home = ({ stats }) => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);

      try {
        const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/v1/post`, {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });

        if (!response.ok) {
          throw new Error(`Error ${response.status}: ${response.statusText}`);
        }

        const result = await response.json();

        // Sort posts by _id in descending order
        const sortedPosts = result.data.sort((a, b) => b._id.localeCompare(a._id));
        setAllPosts(sortedPosts);
      } catch (err) {
        console.error('Error fetching posts:', err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchPosts();

    // Cleanup timeout on unmount
    return () => {
      if (searchTimeout) {
        clearTimeout(searchTimeout);
      }
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSearchChange = (e) => {
    const query = e.target.value.toLowerCase();
    const trimmedQuery = query.trim();
    setSearchText(query);

    clearTimeout(searchTimeout);

    setSearchTimeout(
      setTimeout(() => {
        if (trimmedQuery === '') {
          setSearchedResults(null);
          return;
        }

        const searchResult = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(trimmedQuery) ||
            item.prompt.toLowerCase().includes(trimmedQuery)
        );

        setSearchedResults(searchResult);
      }, 500)
    );
  };

  const renderData = searchText ? searchedResults : allPosts;
  const renderTitle = searchText ? "No Search Results Found" : "No posts found";

  return (
    <section className="max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-8 md:gap-6">
        <div>
          <h1 className="font-extrabold text-[#10131f] text-[32px]">Artofficial</h1>
          <p className="mt-2 text-[#10131f] text-[16px]">
            Explore a collection of imaginative images generated by OpenAI's GPT Image 1.5!
          </p>
        </div>

        {stats && (
          <div className="flex justify-center md:justify-end">
            <StatCard
              imageCount={stats.imageCount}
              userCount={stats.userCount}
            />
          </div>
        )}
      </div>

      <div className="mt-10">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search by name or prompt here"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader trackColor="text-gray-500" spinColor="fill-[#10131f]" />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#10131f] text-xl mb-3">
                Showing results for <span className="text-[#10131f]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              <RenderCards data={renderData} title={renderTitle} />
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;